game:                 # go to line (Ctrl+G):
  A Hat in Time: 4    # line 14
  TUNIC: 0            # line 170
  Muse Dash: 2        # line 208
  VVVVVV: 3           # line 293
name: Fore772
description: Fore772 yaml for Roguelike Async

A Hat in Time:
  start_inventory: {Hookshot Badge: 1}
  plando_items: [{"item": "No Bonk Badge", "location": "careful movement III-3", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Badge Pin", "location": "slots IV-3", "world": "The Cauldron", "force": true, "from_pool": true}, {"items": {"25 Pons": 20}, "locations": ["ranged weapon VI-3", "vitality XII-5", "healing X-3", "stealth II-2", "defense VIII-1", "defense XVIII-2", "careful movement III-2", "attack II-3", "stamina I-4"], "world": "The Cauldron", "force": true, "from_pool": true}]
  EndGoal:
    finale: 10
    rush_hour: 2
  LogicDifficulty: hard # change to moderate, then to normal
  CTRLogic: sprint        # change to scooter, then to time_stop_only
  PonCost: low
  ChapterCost: high       # change to medium, then to low
  DLC: medium               # change to low, then to off
  TrapChance: random-range-low-0-70      # change to 0
  StartWithCompassBadge:
    'true': 25

  death_link: 'true'
  ShuffleAlpineZiplines:
    'false': 10
    'true': 50
  ShuffleStorybookPages: &1-10
    'false': 5
    'true': 50
  ShuffleActContracts: *1-10
  ShuffleSubconPaintings: *1-10
  NoPaintingSkips:
    'false': 25
    'true': 10
  BadgeSellerMinItems: random-low
  BadgeSellerMaxItems: random-high
  ActRandomizer:
    'false': 10
    light: 40
    insanity: 25
  FinaleShuffle:
    'false': 20
    'true': 10
  StartingChapter:
    '1': 25
    '2': 20
    '3': 20
    '4': 20
  ChapterCostIncrement: random-middle
  ChapterCostMinDifference: random-middle
  RandomizeHatOrder:
    'false': 2
    'true': 25
  UmbrellaLogic: random
  CompassBadgeMode:
    closest: 25
    important_only: 1
    important_first: 1
  YarnCostMin: random-low
  YarnCostMax: random-middle
  YarnAvailable: random-middle
  MinExtraYarn: random-middle
  HatItems: &1-2
    'false': 25
    'true': 50
  ExcludeTour: random
  BaseballBat: random
  NyakuzaThugMinShopItems: random-low
  NyakuzaThugMaxShopItems: random-high
  NoTicketSkips: random
  DWShuffle: random
  DWShuffleCountMin: random-low
  DWShuffleCountMax: random-middle
  DWExcludeCandles:
    'false': 1
    'true': 25
  DWTimePieceRequirement: random-middle
  triggers:
    - option_category: A Hat in Time
      option_name: PonCost
      option_result: high
      options:
        A Hat in Time:
          MinPonCost: 100
          MaxPonCost: 400
          MetroMinPonCost: 60
          MetroMaxPonCost: 220
    - option_category: A Hat in Time
      option_name: PonCost
      option_result: medium
      options:
        A Hat in Time:
          MinPonCost: 50
          MaxPonCost: 250
          MetroMinPonCost: 30
          MetroMaxPonCost: 130
    - option_category: A Hat in Time
      option_name: PonCost
      option_result: low
      options:
        A Hat in Time:
          MinPonCost: 10
          MaxPonCost: 30
          MetroMinPonCost: 10
          MetroMaxPonCost: 20
    - option_category: A Hat in Time
      option_name: ChapterCost
      option_result: high
      options:
        A Hat in Time:
          LowestChapterCost: random-high
          HighestChapterCost: random-high
          FinalChapterMinCost: random-high
          FinalChapterMaxCost: random-high
    - option_category: A Hat in Time
      option_name: ChapterCost
      option_result: medium
      options:
        A Hat in Time:
          MinPonCost: random-middle
          MaxPonCost: random-middle
          MetroMinPonCost: random-middle
          MetroMaxPonCost: random-middle
    - option_category: A Hat in Time
      option_name: ChapterCost
      option_result: low
      options:
        A Hat in Time:
          MinPonCost: random-low
          MaxPonCost: random-low
          MetroMinPonCost: random-low
          MetroMaxPonCost: random-low
    - option_category: A Hat in Time
      option_name: DLC
      option_result: high
      options:
        A Hat in Time:
          EnableDLC1: true
          Tasksanity: true
          TasksanityCheckCount: random-range-middle-5-25
          EnableDLC2: true
          EnableDeathWish: true
    - option_category: A Hat in Time
      option_name: DLC
      option_result: medium
      options:
        A Hat in Time:
          EnableDLC1: *1-2
          Tasksanity: true
          TasksanityCheckCount: random-range-low-2-18
          EnableDLC2: *1-2
          EnableDeathWish:
            'false': 50
            'true': 40
    - option_category: A Hat in Time
      option_name: DLC
      option_result: low
      options:
        A Hat in Time:
          EnableDLC1: &2-1
            'false': 50
            'true': 25
          Tasksanity: true
          TasksanityCheckCount: random-range-low-1-8
          EnableDLC2: *2-1

TUNIC:
  plando_items: [{"item": "Gun", "location": "ranged weapon VI-3", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Hero Relic - HP", "location": "vitality XII-5", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Hero Relic - POTION", "location": "healing X-3", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Muffling Bell", "location": "stealth II-2", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Shield", "location": "defense VIII-1", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Hero Relic - DEF", "location": "defense XVIII-2", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Bone Card", "location": "careful movement III-2", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Hero Relic - ATT", "location": "attack II-3", "world": "The Cauldron", "force": true, "from_pool": true}, {"item": "Hero Relic - SP", "location": "stamina I-4", "world": "The Cauldron", "force": true, "from_pool": true}, {"items": {"HP Berry x2": 1, "Lure": 1}, "locations": ["careful movement III-3", "slots IV-3"], "world": "The Cauldron", "force": true, "from_pool": true}]
  keys_behind_bosses:
    'false': 10
    'true': 40 # remove this line
  ability_shuffling: 'true'
  shuffle_ladders: random
  entrance_rando: random
  fixed_shop: random
  start_inventory:
    Money x200: 2
    "Hero's Laurels": 1
  fool_traps:
   'off': 10
   normal: 20
   double: 30
  hexagon_quest:
    'false': 30
    'true': 10
  hexagon_goal: random
  extra_hexagon_percentage: random
  lanternless:
    'false': 10
  maskless:
    'false': 10
  laurels_zips:
    'false': 10
  ice_grappling:
    easy: 50 # change to easy, then 'off'
  ladder_storage:
    easy: 50 # change to 'off'
  ladder_storage_without_items:
    'false': 10

Muse Dash:
  plando_items: [{"items": {"Extra Life": 10, "Great to Perfect (10 Pack)": 10, "Miss to Great (5 Pack)": 10}, "locations": ["careful movement III-3", "slots IV-3", "ranged weapon VI-3", "vitality XII-5", "healing X-3", "stealth II-2", "defense VIII-1", "defense XVIII-2", "careful movement III-2", "attack II-3", "stamina I-4"], "world": "The Cauldron", "force": true, "from_pool": true}]
  progression balancing: 83
  starting_song_count: '5'
  additional_song_count: random-range-high-40-100 #change to 'random-range-40-100' > random-range-low-40-100
  music_sheet_count_percentage: '40'
  music_sheet_win_count_percentage: '56' #reduce by 11, 4 times
  dlc_packs:
  - Muse Plus
  - CHUNITHM COURSE MUSE
  - maimai DX Limited-time Suite
  - Miku in Museland
  - Rin Len's Mirrorland
  streamer_mode_enabled: 'false'
  song_difficulty_mode: manual
  song_difficulty_min: '11'
  song_difficulty_max: '11'
  song_difficulty_progression: '3' # 4, 5
  grade_needed: A #change to B
  death_link: 'true'
  chosen_traps:
  - Background Freeze Trap
  - Bad Apple Trap
  - Chromatic Aberration Trap
  - Error SFX Trap
  - Focus Line Trap
  - Gray Scale Trap
  - Nyaa SFX Trap
  - Pixelate Trap
  - Ripple Trap
  - Vignette Trap
  trap_count_percentage: 'random-range-5-35'
  start_inventory: {}
  local_items: [Music Sheet]
  triggers:
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '0'
      options:
        Muse Dash:
          song_difficulty_min:
            '10': 100
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '1'
      options:
        Muse Dash:
          song_difficulty_min:
            '9': 100
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '2'
      options:
        Muse Dash:
          song_difficulty_min:
            '7': 50
            '8': 50
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '3'
      options:
        Muse Dash:
          song_difficulty_min:
            '6': 50
            '7': 50
            '8': 50
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '4'
      options:
        Muse Dash:
          song_difficulty_min:
            '0': 50
            '6': 50
            '7': 50
            '8': 50
    - option_category: Muse Dash
      option_name: song_difficulty_progression
      option_result: '5'
      options:
        Muse Dash:
          song_difficulty_min:
            '0': 50
            '6': 50
            '7': 50


VVVVVV:
  plando_items: [{"items": {"Trinket 13": 2, "Trinket 14": 2, "Trinket 15": 2, "Trinket 16": 2, "Trinket 17": 2, "Trinket 18": 2, "Trinket 19": 2, "Trinket 20": 2}, "locations": ["careful movement III-3", "slots IV-3", "ranged weapon VI-3", "vitality XII-5", "healing X-3", "stealth II-2", "defense VIII-1", "defense XVIII-2", "careful movement III-2", "attack II-3", "stamina I-4"], "world": "The Cauldron", "force": true, "from_pool": true}]
  excluded_locations: ["Prize for the Reckless", "Edge Games"] # Upgrades: Hard Way as excluded location
  door_cost: random-range-high-1-3 #change to 'random-range-1-3' > random-range-low-1-3
  death_link_amnesty: 10 # Upgrades: Set to 10 > 15 > 20 > 25 > 30 > 50
  music_rando: 'true'
  area_rando: 'true'
  area_cost: 'true'
  death_link: 'true'
  start_inventory: {Trinket 01: 1}

triggers:
  - option_category: null
    option_name: game
    option_result: A Hat in Time
    options:
      null:
        name: ARogueinTime772
  - option_category: null
    option_name: game
    option_result: TUNIC
    options:
      null:
        name: Rogue772nic
  - option_category: null
    option_name: game
    option_result: Muse Dash
    options:
      null:
        name: DashingRogue772
  - option_category: null
    option_name: game
    option_result: VVVVVV
    options:
      null:
        name: RRRRRRogue772
